#[derive(Debug, Clone, Copy)]
pub(crate) struct CountryCode {
    pub display: &'static str,
    pub alpha: &'static str,
    pub numeric: i16,
}

impl CountryCode {
    pub const AU: CountryCode = CountryCode {
        display: "Australia",
        alpha: "AUS",
        numeric: 36,
    };

    pub const CA: CountryCode = CountryCode {
        display: "Canada",
        alpha: "CAN",
        numeric: 124,
    };

    pub const CH: CountryCode = CountryCode {
        display: "Switzerland",
        alpha: "CHE",
        numeric: 756,
    };

    pub const US: CountryCode = CountryCode {
        display: "united States",
        alpha: "USA",
        numeric: 840,
    };
}

pub(crate) enum MediaLanguage {
    Afrikaans,
    Amharic,
    Arabic,
    Mapudungun,
    Assamese,
    Azerbaijani,
    Bashkir,
    Belarusian,
    Bengali,
    Tibetan,
    Breton,
    Bosnian,
    Catalan,
    Corsican,
    Czech,
    Welsh,
    Danish,
    German,
    LowerSorbian,
    Divehi,
    Greek,
    English,
    Spanish,
    Estonian,
    Basque,
    Persian,
    Finnish,
    Filipino,
    Faroese,
    French,
    Frisian,
    Irish,
    ScottishGaelic,
    Galician,
    Alsatian,
    Gujarati,
    Hausa,
    Hebrew,
    Hindi,
    Croatian,
    UpperSorbian,
    Hungarian,
    Armenian,
    Indonesian,
    Igbo,
    Yi,
    Icelandic,
    Italian,
    Inuktitut,
    Japanese,
    Georgian,
    Kazakh,
    Greenlandic,
    Khmer,
    Kannada,
    Korean,
    Konkani,
    Kyrgyz,
    Luxembourgish,
    Lao,
    Lithuanian,
    Latvian,
    Maori,
    Macedonian,
    Malayalam,
    Mongolian,
    Mohawk,
    Marathi,
    Malay,
    Maltese,
    Burmese,
    Norwegian,
    Nepali,
    Dutch,
    Sesotho,
    Occitan,
    Odia,
    Punjabi,
    Polish,
    Dari,
    Pashto,
    Portuguese,
    Quechua,
    Kiche,
    Romansh,
    Russian,
    Kinyarwanda,
    Sanskrit,
    Yakut,
    SamiNorthern,
    Sinhala,
    Slovak,
    Slovenian,
    SamiSouthern,
    SamiLule,
    SamiInari,
    SamiSkolt,
    Albanian,
    Serbian,
    Swedish,
    Kiswahili,
    Syriac,
    Tamil,
    Telugu,
    Tajik,
    Thai,
    Turkmen,
    Tswana,
    Turkish,
    Tatar,
    Tamazight,
    Uyghur,
    Ukrainian,
    Urdu,
    Uzbek,
    Vietnamese,
    Wolof,
    Xhosa,
    Yoruba,
    Chinese,
    Zulu,
}

impl MediaLanguage {
    pub fn title(self) -> String {
        match self {
            Afrikaans => "Afrikaans".to_string(),
            Amharic => "አማርኛ".to_string(),
            Arabic => "العربية".to_string(),
            Mapudungun => "Mapudungun".to_string(),
            Assamese => "অসমীয়া".to_string(),
            Azerbaijani => "Azərbaycan­lı".to_string(),
            Bashkir => "Башҡорт".to_string(),
            Belarusian => "беларуская".to_string(),
            Bulgarian => "български".to_string(),
            Bengali => "বাংলা".to_string(),
            Tibetan => "བོད་ཡིག".to_string(),
            Breton => "brezhoneg".to_string(),
            Bosnian => "bosanski/босански".to_string(),
            Catalan => "català".to_string(),
            Corsican => "Corsu".to_string(),
            Czech => "čeština".to_string(),
            Welsh => "Cymraeg".to_string(),
            Danish => "dansk".to_string(),
            German => "Deutsch".to_string(),
            LowerSorbian => "dolnoserbšćina".to_string(),
            Divehi => "ދިވެހިބަސް".to_string(),
            Greek => "ελληνικά".to_string(),
            English => "English".to_string(),
            Spanish => "español".to_string(),
            Estonian => "eesti".to_string(),
            Basque => "euskara".to_string(),
            Persian => "فارسى".to_string(),
            Finnish => "suomi".to_string(),
            Filipino => "Filipino".to_string(),
            Faroese => "føroyskt".to_string(),
            French => "français".to_string(),
            Frisian => "Frysk".to_string(),
            Irish => "Gaeilge".to_string(),
            ScottishGaelic => "Gàidhlig".to_string(),
            Galician => "galego".to_string(),
            Alsatian => "Elsässisch".to_string(),
            Gujarati => "ગુજરાતી".to_string(),
            Hausa => "Hausa".to_string(),
            Hebrew => "עברית".to_string(),
            Hindi => "हिंदी".to_string(),
            Croatian => "hrvatski".to_string(),
            UpperSorbian => "hornjoserbšćina".to_string(),
            Hungarian => "magyar".to_string(),
            Armenian => "Հայերեն".to_string(),
            Indonesian => "Bahasa Indonesia".to_string(),
            Igbo => "Igbo".to_string(),
            Yi => "ꆈꌠꁱꂷ".to_string(),
            Icelandic => "íslenska".to_string(),
            Italian => "italiano".to_string(),
            Inuktitut => "Inuktitut /ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ)".to_string(),
            Japanese => "日本語".to_string(),
            Georgian => "ქართული".to_string(),
            Kazakh => "Қазақша".to_string(),
            Greenlandic => "kalaallisut".to_string(),
            Khmer => "ខ្មែរ".to_string(),
            Kannada => "ಕನ್ನಡ".to_string(),
            Korean => "한국어/韓國語|조선말/朝鮮말".to_string(),
            Konkani => "कोंकणी".to_string(),
            Kyrgyz => "Кыргыз".to_string(),
            Luxembourgish => "Lëtzebuergesch".to_string(),
            Lao => "ລາວ".to_string(),
            Lithuanian => "lietuvių".to_string(),
            Latvian => "latviešu".to_string(),
            Maori => "Reo Māori".to_string(),
            Macedonian => "македонски јазик".to_string(),
            Malayalam => "മലയാളം".to_string(),
            Mongolian => "Монгол хэл/ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ".to_string(),
            Mohawk => "Kanien'kéha".to_string(),
            Marathi => "मराठी".to_string(),
            Malay => "Bahasa Malaysia".to_string(),
            Maltese => "Malti".to_string(),
            Burmese => "Myanmar".to_string(),
            Norwegian => "norsk".to_string(),
            Nepali => "नेपाली (नेपाल)".to_string(),
            Dutch => "Nederlands".to_string(),
            Sesotho => "Sesotho sa Leboa".to_string(),
            Occitan => "Occitan".to_string(),
            Odia => "ଓଡ଼ିଆ".to_string(),
            Punjabi => "ਪੰਜਾਬੀ".to_string(),
            Polish => "polski".to_string(),
            Dari => "درى".to_string(),
            Pashto => "پښتو".to_string(),
            Portuguese => "Português".to_string(),
            Quechua => "runasimi".to_string(),
            Kiche => "K'iche".to_string(),
            Romansh => "Rumantsch".to_string(),
            Romanian => "română".to_string(),
            Russian => "русский".to_string(),
            Kinyarwanda => "Kinyarwanda".to_string(),
            Sanskrit => "संस्कृत".to_string(),
            Yakut => "саха".to_string(),
            SamiNorthern => "davvisámegiella".to_string(),
            Sinhala => "සිංහල".to_string(),
            Slovak => "slovenčina".to_string(),
            Slovenian => "slovenski".to_string(),
            SamiSouthern => "åarjelsaemiengiele".to_string(),
            SamiLule => "julevusámegiella".to_string(),
            SamiInari => "sämikielâ".to_string(),
            SamiSkolt => "sääm´ǩiõll".to_string(),
            Albanian => "shqipe".to_string(),
            Serbian => "srpski/српски".to_string(),
            Swedish => "svenska".to_string(),
            Kiswahili => "Kiswahili".to_string(),
            Syriac => "ܣܘܪܝܝܐ".to_string(),
            Tamil => "தமிழ்".to_string(),
            Telugu => "తెలుగు".to_string(),
            Tajik => "Тоҷикӣ".to_string(),
            Thai => "ไทย".to_string(),
            Turkmen => "türkmençe".to_string(),
            Tswana => "Setswana".to_string(),
            Turkish => "Türkçe".to_string(),
            Tatar => "Татарча".to_string(),
            Tamazight => "Tamazight".to_string(),
            Uyghur => "ئۇيغۇرچە".to_string(),
            Ukrainian => "українська".to_string(),
            Urdu => "اُردو".to_string(),
            Uzbek => "U'zbek/Ўзбек".to_string(),
            Vietnamese => "Tiếng Việt/㗂越".to_string(),
            Wolof => "Wolof".to_string(),
            Xhosa => "isiXhosa".to_string(),
            Yoruba => "Yoruba".to_string(),
            Chinese => "中文".to_string(),
            Zulu => "isiZulu".to_string(),
            _ => "English".to_string(),
        }
    }

    pub fn code(&self) -> String {
        match self {
            Afrikaans => "af".to_string(),
            Amharic => "am".to_string(),
            Arabic => "ar".to_string(),
            Mapudungun => "arn".to_string(),
            Assamese => "as".to_string(),
            Azerbaijani => "az".to_string(),
            Bashkir => "ba".to_string(),
            Belarusian => "be".to_string(),
            Bulgarian => "bg".to_string(),
            Bengali => "bn".to_string(),
            Tibetan => "bo".to_string(),
            Breton => "br".to_string(),
            Bosnian => "bs".to_string(),
            Catalan => "ca".to_string(),
            Corsican => "co".to_string(),
            Czech => "cs".to_string(),
            Welsh => "cy".to_string(),
            Danish => "da".to_string(),
            German => "de".to_string(),
            LowerSorbian => "dsb".to_string(),
            Divehi => "dv".to_string(),
            Greek => "el".to_string(),
            English => "en".to_string(),
            Spanish => "es".to_string(),
            Estonian => "et".to_string(),
            Basque => "eu".to_string(),
            Persian => "fa".to_string(),
            Finnish => "fi".to_string(),
            Filipino => "fil".to_string(),
            Faroese => "fo".to_string(),
            French => "fr".to_string(),
            Frisian => "fy".to_string(),
            Irish => "ga".to_string(),
            ScottishGaelic => "gd".to_string(),
            Galician => "gl".to_string(),
            Alsatian => "gsw".to_string(),
            Gujarati => "gu".to_string(),
            Hausa => "ha".to_string(),
            Hebrew => "he".to_string(),
            Hindi => "hi".to_string(),
            Croatian => "hr".to_string(),
            UpperSorbian => "hsb".to_string(),
            Hungarian => "hu".to_string(),
            Armenian => "hy".to_string(),
            Indonesian => "id".to_string(),
            Igbo => "ig".to_string(),
            Yi => "ii".to_string(),
            Icelandic => "is".to_string(),
            Italian => "it".to_string(),
            Inuktitut => "iu".to_string(),
            Japanese => "ja".to_string(),
            Georgian => "ka".to_string(),
            Kazakh => "kk".to_string(),
            Greenlandic => "kl".to_string(),
            Khmer => "km".to_string(),
            Kannada => "kn".to_string(),
            Korean => "ko".to_string(),
            Konkani => "kok".to_string(),
            Kyrgyz => "ky".to_string(),
            Luxembourgish => "lb".to_string(),
            Lao => "lo".to_string(),
            Lithuanian => "lt".to_string(),
            Latvian => "lv".to_string(),
            Maori => "mi".to_string(),
            Macedonian => "mk".to_string(),
            Malayalam => "ml".to_string(),
            Mongolian => "mn".to_string(),
            Mohawk => "moh".to_string(),
            Marathi => "mr".to_string(),
            Malay => "ms".to_string(),
            Maltese => "mt".to_string(),
            Burmese => "my".to_string(),
            Norwegian => "no".to_string(),
            Nepali => "ne".to_string(),
            Dutch => "nl".to_string(),
            Sesotho => "st".to_string(),
            Occitan => "oc".to_string(),
            Odia => "or".to_string(),
            Punjabi => "pa".to_string(),
            Polish => "pl".to_string(),
            Dari => "prs".to_string(),
            Pashto => "ps".to_string(),
            Portuguese => "pt".to_string(),
            Quechua => "qu".to_string(),
            Kiche => "quc".to_string(),
            Romansh => "rm".to_string(),
            Romanian => "ro".to_string(),
            Russian => "ru".to_string(),
            Kinyarwanda => "rw".to_string(),
            Sanskrit => "sa".to_string(),
            Yakut => "sah".to_string(),
            SamiNorthern => "se".to_string(),
            Sinhala => "si".to_string(),
            Slovak => "sk".to_string(),
            Slovenian => "sl".to_string(),
            SamiSouthern => "sma".to_string(),
            SamiLule => "smj".to_string(),
            SamiInari => "smn".to_string(),
            SamiSkolt => "sms".to_string(),
            Albanian => "sq".to_string(),
            Serbian => "sr".to_string(),
            Swedish => "sv".to_string(),
            Kiswahili => "sw".to_string(),
            Syriac => "syc".to_string(),
            Tamil => "ta".to_string(),
            Telugu => "te".to_string(),
            Tajik => "tg".to_string(),
            Thai => "th".to_string(),
            Turkmen => "tk".to_string(),
            Tswana => "tn".to_string(),
            Turkish => "tr".to_string(),
            Tatar => "tt".to_string(),
            Tamazight => "tzm".to_string(),
            Uyghur => "ug".to_string(),
            Ukrainian => "uk".to_string(),
            Urdu => "ur".to_string(),
            Uzbek => "uz".to_string(),
            Vietnamese => "vi".to_string(),
            Wolof => "wo".to_string(),
            Xhosa => "xh".to_string(),
            Yoruba => "yo".to_string(),
            Chinese => "zh".to_string(),
            Zulu => "zu".to_string(),
            _ => "English".to_string(),
        }
    }
}
